### ISSUE TITLE
SD配置之后发现调用接口报错

### ISSUE THREAD

**Issue by sxzq46** [yangjian102621/geekai#164]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Linux

### Bug 描述 📝

ERROR	sd/service.go:304	任务执行失败：error http status code: {"error":null}
接口文档显示的接口是：
![image](https://github.com/yangjian102621/chatgpt-plus/assets/2561843/b7c8264d-88e4-452e-ac74-f2396321b269)

### 重现步骤 🕹

修改完配置，启动最新的秋叶SD之后，在页面立即生成的时候，api日志报错：ERROR	sd/service.go:304	任务执行失败：error http status code: {"error":null}

### 你的应用配置信息

```toml
[[SdConfigs]]
  Enabled = true
  ApiURL = "http://10.147.17.90:7860"
  Txt2ImgJsonPath = "res/sd/text2img.json"
```
